# Generated by Django 5.2.14 on 2026-06-10 18:07

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('voice', 'Voice'), ('document', 'Document'), ('text', 'Text')], max_length=10)),
                ('title', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('key_ideas', models.JSONField(blank=True, default=list)),
                ('transcript', models.JSONField(blank=True, null=True)),
                ('source_key', models.TextField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('status', models.CharField(choices=[('pending_upload', 'Pending upload'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending_upload', max_length=16)),
                ('pipeline_attempts', models.IntegerField(default=0)),
                ('search_vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('title', 'body', 'summary', config='english'), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pinned', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='core.filament')),
            ],
        ),
        migrations.CreateModel(
            name='FilamentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filament')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
            ],
        ),
        migrations.AddField(
            model_name='filament',
            name='tags',
            field=models.ManyToManyField(related_name='filaments', through='core.FilamentTag', to='core.tag'),
        ),
        migrations.CreateModel(
            name='FilamentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_source', to='core.filament')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_target', to='core.filament')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'target'), name='uniq_link_pair')],
            },
        ),
        migrations.AddConstraint(
            model_name='filamenttag',
            constraint=models.UniqueConstraint(fields=('filament', 'tag'), name='uniq_filament_tag'),
        ),
        migrations.AddIndex(
            model_name='filament',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='filament_search_gin'),
        ),
    ]
