# Generated by Django 5.2.14 on 2026-06-01 22:44

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_enable_pgvector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('url', 'URL'), ('pdf', 'PDF'), ('note', 'Note'), ('transcript', 'Transcript')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('raw_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('chunk_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.filament')),
            ],
            options={
                'ordering': ['filament', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('query_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='filament',
            index=models.Index(fields=['user', '-created_at'], name='core_filame_user_id_b3505c_idx'),
        ),
        migrations.AddIndex(
            model_name='filament',
            index=models.Index(fields=['user', 'content_type'], name='core_filame_user_id_80199b_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['filament', 'chunk_index'], name='core_chunk_filamen_4418af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chunk',
            unique_together={('filament', 'chunk_index')},
        ),
    ]
