# Generated by Django 5.2.14 on 2026-06-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='filamentlink',
            constraint=models.CheckConstraint(condition=models.Q(('source_id__lt', models.F('target_id'))), name='link_pair_canonical_order'),
        ),
    ]
